server:
  port: ${appPort:9092}

# Spring MVC actuator endpoints available via /admin/info, /admin/health, ...
server.servlet-path: /
management.context-path: /admin

info:
  app:
    name: kaloori
  build:
    version: V1

security:
  key: thamizh@amizh

spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    username: amizhthdev
    password: amizhthdevdb123
    url: jdbc:postgresql://amizhthdev.c41mzmwqiqbp.ap-south-1.rds.amazonaws.com:5432/smsplatform?stringtype=unspecified&currentSchema=public
       
aws:
  s3:
    bucket_name: ammatrimony
  access:
    key: AKIARQ5A67NEG6WLYOAF
  secret:
    key: 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
  region: AP_SOUTH_1

upload:
  path: /tmp
 # Bring Postgres docker images using: 
# docker run -d -p 5532:5432 -e DB_NAME=db_dvdrental -e DB_USER=user_dvdrental -e DB_PASSWD=changeit asimio/db_dvdrental:latest
# 172.16.69.133 = Fusion VM Docker host, 5532 Docker host port mapped to container port
